### ISSUE TITLE
Error on opening program on demand

### ISSUE THREAD

**Issue by SimonDeRidder** [add-ons/plugin.video.vrt.nu#1111]
### Describe the bug ###

Since ~9 july, live TV works, but opening a specific program doesn't work.
E.g. opening "Het Journaal" from "My Favourites" - "My Programs" gives error (see log below).
Search will give results, but they can't be played.

### Additional context ###

- Operating system: Ubuntu 22.04.2 LTS
- Kodi version: 20.2
- Addon version: 2.5.22
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```
2023-07-10 16:15:47.669 T:16630 critical <general>: [plugin.video.vrt.nu] JSON ValueError: Expecting value: line 1 column 1 (char 0)
2023-07-10 16:15:47.699 T:16630   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/home/watson/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/home/watson/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 353, in run
                                                       plugin.run(argv)
                                                     File "/home/watson/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/watson/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/watson/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 155, in programs
                                                       VRTPlayer().show_episodes_menu(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                                     File "/home/watson/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 249, in show_episodes_menu
                                                       episodes, sort, ascending, content = get_episodes(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                                     File "/home/watson/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 977, in get_episodes
                                                       api_data = get_seasons(program_name)
                                                     File "/home/watson/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 1018, in get_seasons
                                                       seasons = season_json.get('details').get('data').get('program').get('seasons')
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
```

**Comment by PeterCloet** [comment]
Same issue here on Libreelec 10.0.2; Kodi 19.4.
I found one update available in the add-on repo but that didn't fix the issue.

**Comment by ErwinBaeyens** [comment]
Same error on raspberrypy libreelec 9.2.8
VRT Max plugin 2.5.22 
NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/balthazar
2023-07-10 23:27:54.936 T:2407519040   ERROR: [plugin.video.vrt.nu] JSON ValueError: No JSON object could be decoded
2023-07-10 23:27:54.944 T:2407519040   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                run(argv)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 353, in run
                                                plugin.run(argv)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 155, in programs
                                                VRTPlayer().show_episodes_menu(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 249, in show_episodes_menu
                                                episodes, sort, ascending, content = get_episodes(program_name=program_name, season_name=season_name, end_cursor=end_cursor)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 977, in get_episodes
                                                api_data = get_seasons(program_name)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/api.py", line 1018, in get_seasons
                                                seasons = season_json.get('details').get('data').get('program').get('seasons')
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
2023-07-10 23:27:55.032 T:2889708352   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/balthazar
2023-07-10 23:27:55.033 T:3011822976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/balthazar) failed
2023-07-10 23:29:56.211 T:2415911744  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/categories
2023-07-10 23:29:56.366 T:2415911744  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/

**Comment by bhooyberghs** [comment]
Thx ! It works on kodi 20.1 on windows 11 and librelec 11.0.1 !

**Comment by SimonDeRidder** [comment]
Confirmed, works for me as well!

**Comment by LeEcHeR123** [comment]
Comfirmed working. Thanks!

**Comment by Bart80-1** [comment]
Hi, has this release been pushed yet to Kodi addon registry?
[https://kodi.tv/addons/matrix/plugin.video.vrt.nu/](https://kodi.tv/addons/matrix/plugin.video.vrt.nu/) still refers to 2.5.22

**Comment by mediaminister** [comment]
It should be available now.
